export enum STATE_NAMES {
    ALABAMA = "Alabama",
    ALASKA = "Alaska",
    ARIZONA = "Arizona",
    ARKANSAS = "Arkansas",
    CALIFORNIA = "California",
    COLORADO = "Colorado",
    CONNECTICUT = "Connecticut",
    DELAWARE = "Delaware",
    DISTRICT_OF_COLUMBIA = "District of Columbia",
    FLORIDA = "Florida",
    GEORGIA = "Georgia",
    HAWAII = "Hawaii",
    IDAHO = "Idaho",
    ILLINOIS = "Illinois",
    INDIANA = "Indiana",
    IOWA = "Iowa",
    KANSAS = "Kansas",
    KENTUCKY = "Kentucky",
    LOUISIANA = "Louisiana",
    MAINE = "Maine",
    MARYLAND = "Maryland",
    MASSACHUSETTS = "Massachusetts",
    MICHIGAN = "Michigan",
    MINNESOTA = "Minnesota",
    MISSISSIPPI = "Mississippi",
    MISSOURI = "Missouri",
    MONTANA = "Montana",
    NEBRASKA = "Nebraska",
    NEVADA = "Nevada",
    NEW_HAMPSHIRE = "New Hampshire",
    NEW_JERSEY = "New Jersey",
    NEW_MEXICO = "New Mexico",
    NEW_YORK = "New York",
    NORTH_CAROLINA = "North Carolina",
    NORTH_DAKOTA = "North Dakota",
    OHIO = "Ohio",
    OKLAHOMA = "Oklahoma",
    OREGON = "Oregon",
    PENNSYLVANIA = "Pennsylvania",
    RHODE_ISLAND = "Rhode Island",
    SOUTH_CAROLINA = "South Carolina",
    SOUTH_DAKOTA = "South Dakota",
    TENNESSEE = "Tennessee",
    TEXAS = "Texas",
    UTAH = "Utah",
    VERMONT = "Vermont",
    VIRGINIA = "Virginia",
    WASHINGTON = "Washington",
    WEST_VIRGINIA = "West Virginia",
    WISCONSIN = "Wisconsin",
    WYOMING = "Wyoming",
}

export enum TERRITORY_NAMES {
    PUERTO_RICO = "Puerto Rico",
}

export const STATES = [
    STATE_NAMES.ARIZONA,
    STATE_NAMES.ARKANSAS,
    STATE_NAMES.CALIFORNIA,
    STATE_NAMES.COLORADO,
    STATE_NAMES.CONNECTICUT,
    STATE_NAMES.GEORGIA,
    STATE_NAMES.HAWAII,
    STATE_NAMES.ILLINOIS,
    STATE_NAMES.INDIANA,
    STATE_NAMES.LOUISIANA,
    STATE_NAMES.MINNESOTA,
    STATE_NAMES.MISSISSIPPI,
    STATE_NAMES.MONTANA,
    STATE_NAMES.NEW_MEXICO,
    STATE_NAMES.NORTH_DAKOTA,
    STATE_NAMES.OKLAHOMA,
    STATE_NAMES.PENNSYLVANIA,
    STATE_NAMES.TENNESSEE,
    STATE_NAMES.VIRGINIA,
    TERRITORY_NAMES.PUERTO_RICO,
    STATE_NAMES.DELAWARE,
    STATE_NAMES.WEST_VIRGINIA,
    STATE_NAMES.WISCONSIN,
    STATE_NAMES.WYOMING,
    STATE_NAMES.ALABAMA,
    STATE_NAMES.ALASKA,
    STATE_NAMES.FLORIDA,
    STATE_NAMES.IDAHO,
    STATE_NAMES.KANSAS,
    STATE_NAMES.NEW_JERSEY,
    STATE_NAMES.NORTH_CAROLINA,
    STATE_NAMES.SOUTH_CAROLINA,
    STATE_NAMES.WASHINGTON,
    STATE_NAMES.VERMONT,
    STATE_NAMES.UTAH,
    STATE_NAMES.IOWA,
    STATE_NAMES.KENTUCKY,
    STATE_NAMES.MAINE,
    STATE_NAMES.MASSACHUSETTS,
    STATE_NAMES.MICHIGAN,
    STATE_NAMES.MISSOURI,
    STATE_NAMES.NEBRASKA,
    STATE_NAMES.NEVADA,
    STATE_NAMES.NEW_HAMPSHIRE,
    STATE_NAMES.NEW_YORK,
    STATE_NAMES.OHIO,
    STATE_NAMES.OREGON,
    STATE_NAMES.RHODE_ISLAND,
    STATE_NAMES.SOUTH_DAKOTA,
    STATE_NAMES.TEXAS,
    STATE_NAMES.DISTRICT_OF_COLUMBIA,
    STATE_NAMES.MARYLAND
];

export enum QuizType {
    LICENSE_PLATES,
    ADOPT_A_HIGHWAY,
    STATE_HIGHWAY,
    COUNTY_SECONDARY_HIGHWAY,
}
