export enum Path {
    HOME = "/home",
    ABOUT = "/about-me",
    PROJECTS = "/resume",
    XGEO = "/xgeo",
    XGEO_US = "/xgeo/us/license-plates",
    XGEO_US_ADOPT_A_HIGHWAY = "/xgeo/us/adopt-a-highway",
    XGEO_US_STATE_HIGHWAY = "/xgeo/us/state-highway",
    XGEO_US_COUNTY_SECONDARY_HIGHWAY = "/xgeo/us/county-secondary-highway",
    XGEO_US_STATE_FLAGS = "/xgeo/us/state-flags",
    XGEO_NA_TREE_SPECIES = "/xgeo/na/tree-species",
    XGEO_BR = "/xgeo/brazil/phone-codes",
    XGEO_MONG = "/xgeo/mongolia/driving-direction",
    SOON = "/coming-soon",
    CREDITS = "/credits",
    EIGHTYEIGHT = "/88x31",
    DIGICAM = "/digicam",
    VISITORS = "/visitors",
    SUPPORT = "/support",
    ANNOUNCEMENTS = "/patch-notes",
    TRAVEL_LOG = "/travel-log",
}
