export const KANJI = [
    ["中央", ["chuo"], ["central"]],
    ["中", ["naka"], ["central", "inside"]],
    ["北", ["hoko", "kita"], ["north"]],
    ["南", ["nam", "minami"], ["south"]],
    ["東", ["to", "higashi"], ["east"]],
    ["西", ["sai", "zai", "nishi"], ["west"]],
    ["上", ["kami", "ue"], ["upper"]],
    ["下", ["shimo", "shita"], ["lower", "under"]],
    ["右", ["u"], ["right"]],
    ["左", ["sa"], ["left"]],
    ["横", ["yoko"], ["side"]],

    ["本", ["hon", "moto"], ["origin"]],
    ["新", ["shin"], ["new"]],
    ["古", ["furu", "ko", "go"], ["old"]],
    ["長", ["naga"], ["long"]],
    ["前", ["mae"], ["front"]],
    ["内", ["uchi"], ["inside"]],
    ["外", ["soto", "gae"], ["outside"]],
    ["高", ["taka", "ko"], ["tall"]],
    ["大", ["o"], ["big"]],
    ["小", ["ko", "o"], ["small"]],
    ["広", ["hiro"], ["wide"]],

    ["白", ["shiro"], ["white"]],
    ["黒", ["kuro"], ["black"]],
    ["赤", ["aka"], ["red"]],
    ["青", ["ao"], ["blue"]],
    ["黄", ["ki"], ["yellow"]],
    ["緑", ["midori"], ["green"]],
    ["紫", ["murasaki"], ["purple"]],
    ["灰", ["hai"], ["gray"]],
    ["茶", ["cha"], ["brown", "tea"]],

    ["県", ["-ken"], ["prefecture"]],
    ["府", ["fu"], ["prefecture"]],
    ["郡", ["-gun"], ["district"]],
    ["市", ["-shi"], ["city"]],
    ["区", ["-ku"], ["ward"]],
    ["町", ["-machi", "-chō"], ["town"]],
    ["村", ["-mura", "-son"], ["village"]],
    ["通", ["-dori", "-michi", "-do"], ["street"]],
    ["条", ["-jō"], ["street"]],
    ["港", ["minato"], ["harbor"]],
    ["津", ["tsu"], ["harbor"]],
    ["宿", ["shuku", "-juku"], ["station town"]],
    ["駅", ["eki"], ["station"]],
    ["橋", ["-hashi", "-bashi"], ["bridge"]],
    ["屋", ["-ya"], ["shop"]],
    ["京", ["kyō"], ["capital"]],

    ["浜", ["hama"], ["beach"]],
    ["半島", ["hanto"], ["peninsula"]],
    ["石", ["ishi"], ["rock"]],
    ["岩", ["iwa"], ["rock"]],
    ["泉", ["izumi"], ["spring"]],
    ["海峡", ["kaikyo"], ["strait"]],
    ["川", ["kawa", "-gawa"], ["river"]],
    ["河", ["kawa", "-gawa"], ["river (big)"]],
    ["湖", ["ko"], ["lake"]],
    ["灘", ["nada"], ["sea"]],
    ["岡", ["oka"], ["hill"]],
    ["崎", ["-saki", "-zaki"], ["promontory"]],
    ["岬", ["misaki"], ["cape"]],
    ["山", ["yama", "san", "-zan"], ["mountain"]],
    ["沢", ["sawa", "-zawa"], ["swamp"]],
    ["島", ["shima", "-jima"], ["island"]],
    ["谷", ["tani", "-dani", "-ya"], ["valley"]],
    ["湾", ["wan"], ["bay"]],
    ["江", ["e"], ["bay"]],
    ["浦", ["ura"], ["bay"]],
    ["森", ["mori"], ["forest"]],
    ["木", ["ki", "-gi"], ["tree"]],
    ["松", ["matsu"], ["pine"]],
    ["杉", ["sugi"], ["japanese cedar"]],
    ["田", ["ta", "-da"], ["rice paddy"]],
    ["原", ["hara"], ["meadow"]],
    ["野", ["no"], ["field"]],
    ["台", ["tai", "dai"], ["plateau"]],
    ["海", ["umi", "-kai"], ["sea"]],
    ["池", ["ike"], ["pond"]],
    ["平", ["hira", "-taira"], ["plain"]],
    ["尾", ["o"], ["ridge"]],
    ["坂", ["saka"], ["slope"]],

    ["福", ["fuku"], ["fortune"]],
    ["仙", ["sen"], ["immortal"]],
    ["富", ["fu", "tomi"], ["wealth"]],
    ["宮", ["miya"], ["shrine"]],
    ["井", ["i"], ["well"]],
    ["吉", ["kichi", "yoshi"], ["lucky"]],
    ["日", ["hi", "nichi"], ["day, sun"]],
    ["徳", ["toku"], ["virtue"]],
    ["和", ["wa"], ["harmony"]],
    ["立", ["tachi", "ritsu"], ["stand"]],
    ["部", ["bu", "be"], ["section"]],
];
